name: pcb-cost-estimator-production
services:
  pcb-cost-estimator-prod:
    build:
      context: ../../
      dockerfile: docker/production/Dockerfile
    image: pcb-cost-estimator-prod
    ports:
      - "5002:3000"
    restart: unless-stopped