name: pcb-cost-estimator-development
services:
  pcb-cost-estimator-dev:
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
    image: pcb-cost-estimator-dev
    ports:
      - "5001:3000"
    restart: unless-stopped